name: RICE
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - pip:
    - PV-ICE=0.3.0
  - python=3.11
  - pip
  # data science
  - ipython
  - numpy
  - pandas
  - matplotlib
  - geopy
#  - urllib
  - requests
#  - itertools
  - plotly
#  - json
  # PV ICE
#  - pip
  # Relog
#  - pip
#  - pip:
#    - julia=1.8